### ISSUE TITLE
pyveg Meta Issue: modifications to pyveg for spatial signatures.

### ISSUE THREAD

**Issue by crangelsmith** [urbangrammarai/timeseries_signatures_archive#2]
Start from forking the `pyveg` repo into the spatial signatures organisation.

Modifications needed (this is not ordered by priority):

- [ ] Remove unnecessary code from the vegetation project (NDVI, network centrality calculations, etc). (issue https://github.com/urbangrammarai/gee_pipeline/issues/3)
- [ ] Check for any other bottleneck that might be making the downloading slower.
- [ ] Investigate GEE cloud filtering updates since 2020 and another pixel-level filtering that can be included in the composite stage (follow the GHSL mosaic methodology as much as possible) (issue https://github.com/urbangrammarai/gee_pipeline/issues/4).
- [ ] Investigate colour normalisation and brightness (cut 2.5% tails). (https://github.com/urbangrammarai/gee_pipeline/issues/7)
- [ ] Investigate filtering images by the time of flight (if relevant).
- [ ] Make the size of chip also part of the config file.  (https://github.com/urbangrammarai/gee_pipeline/issues/5)
- [ ] Modify code and config files to take polygon regions instead of centre points + region size.  Save these regions' info at the large image and chip level (https://github.com/urbangrammarai/gee_pipeline/issues/8). 
- [ ] Save chips as `.npy` or `.npyz` files (currently .png). (https://github.com/urbangrammarai/gee_pipeline/issues/5)
- [ ] Functionality to consistently and efficiently map Great Britain and create a list of polygons. (https://github.com/urbangrammarai/gee_pipeline/issues/6)
- [ ] Investigate ways to export metadata at the pixel level (number of images in the composite per pixel). (https://github.com/urbangrammarai/gee_pipeline/issues/9)
- [ ] New name for `pyveg` and generic documentation (https://github.com/urbangrammarai/gee_pipeline/issues/10).

**Comment by darribas** [comment]
Adding official `pyveg` link for convenience:

https://github.com/alan-turing-institute/monitoring-ecosystem-resilience

**Comment by andrewphilipsmith** [comment]
Have created a fork of the `monitoring-ecosystem-resilience` repo:
https://github.com/urbangrammarai/gee_pipeline

We should be committing changes to this fork.
